// export enum CategoryType {
//     VIVIENDA = "Vivienda",              
//     ALIMENTACION = "Alimentación",       
//     TRANSPORTE = "Transporte",           
//     SALUD = "Salud",                     
//     EDUCACION = "Educación",           
//     ENTRETENIMIENTO = "Entretenimiento",
//     ROPA_ACCESORIOS = "Ropa y Accesorios",
//     CUIDADO_PERSONAL = "Cuidado Personal",
//     MASCOTAS = "Mascotas",               
//     TECNOLOGIA = "Tecnología",          
//     AHORRO_INVERSIONES = "Ahorro e Inversiones", 
//     EMERGENCIAS = "Emergencias",       
//     INGRESOS = "Ingresos",              
//     VIAJES = "Viajes",               
//     HOGAR = "Hogar",                   
//     DEUDAS = "Deudas",               
//     IMPUESTOS = "Impuestos",            
//     REGALOS = "Regalos",               
//     HERRAMIENTAS = "Herramientas",     
//     OTROS = "Otros"                   
//   }
export enum CategoryType {
    HOUSING = "Vivienda",               
    FOOD = "Alimentación",                     
    TRANSPORTATION = "Transporte", 
    HEALTH = "Salud",                 
    EDUCATION = "Educación",           
    ENTERTAINMENT = "Entretenimiento",   
    CLOTHING_ACCESSORIES = "Ropa y Accesorios", 
    PERSONAL_CARE = "Cuidado Personal",   
    PETS = "Mascotas",                     
    TECHNOLOGY = "Tecnología",         
    SAVINGS_INVESTMENTS = "Ahorros e Inversiones", 
    EMERGENCIES = "Emergencias",       
    INCOME = "Ingresos",                 
    TRAVEL = "Viajes",                 
    HOME = "Hogar",                     
    DEBTS = "Deudas",                   
    TAXES = "Impuestos",                   
    GIFTS = "Regalos",                   
    TOOLS = "Herramientas",                   
    OTHERS = "Otros"                  
}
